<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Wheeeee.Core" Version="1.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wheeeee.Calendar37.Core\Wheeeee.Calendar37.Core.csproj" />
  </ItemGroup>

</Project>
