<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wheeeee.Calendar37.BL\Wheeeee.Calendar37.BL.csproj" />
    <ProjectReference Include="..\Wheeeee.Calendar37.Core\Wheeeee.Calendar37.Core.csproj" />
    <ProjectReference Include="..\Wheeeee.Calendar37.Repositories\Wheeeee.Calendar37.Repositories.csproj" />
  </ItemGroup>

</Project>
